/**
 * Seed script — backfill historical attendance + lesson data for Kabiangek Dashboard.
 * 
 * Usage: BLOB_READ_WRITE_TOKEN=... npx tsx scripts/seed.ts
 * 
 * This populates:
 *   - Week of May 25–29, 2026 (all missed — Nilolabs didn't attend)
 *   - Week of June 1–5, 2026  (all missed)
 * 
 * Both weeks marked as "missed" so the cron pipeline knows to HOLD at
 * the May 25 topics until those lessons are actually taught.
 */

import { put } from '@vercel/blob';

const BLOB_TOKEN = process.env.BLOB_READ_WRITE_TOKEN;
if (!BLOB_TOKEN) {
  console.error('❌ BLOB_READ_WRITE_TOKEN environment variable required.');
  console.error('   Get it from: Vercel Dashboard → Storage → Blob → Settings');
  process.exit(1);
}

// ── Lesson topics for each week ──
// These match what was generated by the cron pipeline.

const WEEK_MAY25: Record<string, { topic: string; notesPath?: string; slidesPath?: string }> = {
  '2026-05-25-g7-agriculture':             { topic: 'Knitting Intro: Meaning, Tools, Materials, Basic Stitches' },
  '2026-05-26-g9-pre-tech-studies':        { topic: 'Handling Waste Materials: 8 Types + Safe Handling Methods' },
  '2026-05-26-g7-agriculture':             { topic: 'Knitting Patterns & Techniques' },
  '2026-05-27-g7-agriculture':             { topic: 'Practical Knitting Projects & Review' },
  '2026-05-28-g7-pre-tech-studies':        { topic: 'Metallic vs Non-metallic Materials' },
  '2026-05-29-g9-pre-tech-studies':        { topic: 'Reduce, Reuse & Practical Waste Management' },
  '2026-05-29-g7-pre-tech-studies':        { topic: 'Production of Goods & Services: Meaning, Types, Factors' },
};

const WEEK_JUNE1: Record<string, { topic: string; notesPath?: string; slidesPath?: string }> = {
  '2026-06-01-g7-agriculture':             { topic: 'Crochet: Meaning, Tools, Materials & Basic Stitches' },
  '2026-06-02-g9-pre-tech-studies':        { topic: 'Environmental Conservation: Meaning, Importance & Degradation' },
  '2026-06-02-g7-agriculture':             { topic: 'Crochet Patterns & Advanced Techniques' },
  '2026-06-03-g7-agriculture':             { topic: 'Practical Crochet Projects & Strand 4 Review' },
  '2026-06-04-g7-pre-tech-studies':        { topic: 'Introduction to Entrepreneurship: Meaning of Entrepreneur' },
  '2026-06-05-g9-pre-tech-studies':        { topic: 'Environmental Conservation Methods & Practices' },
  '2026-06-05-g7-pre-tech-studies':        { topic: 'Characteristics of Entrepreneurs & Types of Business Enterprises' },
};

// Attendance: all lessons marked MISSED (false) for both weeks
function buildAttendance(weekData: Record<string, any>) {
  const records: Record<string, any> = {};
  const now = new Date().toISOString();
  for (const lessonId of Object.keys(weekData)) {
    records[lessonId] = {
      lessonId,
      attended: false,
      markedAt: now,
    };
  }
  return { records, lastUpdated: now };
}

async function main() {
  console.log('🌱 Seeding Kabiangek Dashboard...\n');

  // 1. Upload attendance data
  const attendance = {
    records: {
      ...buildAttendance(WEEK_MAY25).records,
      ...buildAttendance(WEEK_JUNE1).records,
    },
    lastUpdated: new Date().toISOString(),
  };

  console.log('📝 Uploading attendance data (14 lessons, all missed)...');
  await put('data/attendance.json', JSON.stringify(attendance, null, 2), {
    access: 'public',
    contentType: 'application/json',
  });
  console.log('   ✅ attendance.json uploaded');

  // 2. Upload lesson metadata for each week
  console.log('\n📚 Uploading lesson metadata...');
  await put('data/lessons/2026-05-25.json', JSON.stringify(WEEK_MAY25, null, 2), {
    access: 'public',
    contentType: 'application/json',
  });
  console.log('   ✅ Week May 25 uploaded');

  await put('data/lessons/2026-06-01.json', JSON.stringify(WEEK_JUNE1, null, 2), {
    access: 'public',
    contentType: 'application/json',
  });
  console.log('   ✅ Week June 1 uploaded');

  console.log('\n🎉 Backfill complete!');
  console.log('   Dashboard now shows May 25 – June 5 as missed lessons.');
  console.log('   The cron pipeline will HOLD topics until attendance is marked.');
}

main().catch((e) => {
  console.error('❌ Seed failed:', e);
  process.exit(1);
});
